#!/bin/sh

KEY="$1"

echo "killing on key $KEY, input $INPUT"

killactive()
{
	WIN=$(xdotool getwindowfocus)
	PID=$(xprop -id "$WIN" | grep '_NET_WM_PID' | awk '{ print $3 }')
	kill "$PID"
}

getevts()
{
	while :; do
		xinput test $INPUT
		sleep 1
	done
}

getkbds()
{
	xinput list | grep -i keyboard | sed 's/.*id=//' | cut -f1
}

killer()
{
INPUT="$1"
	getevts \
		| grep --line-buffered -i "key press *$KEY" \
		| while read -r line; do killactive; done
}

for i in $(getkbds); do
	killer "$i" &
done
