#!/bin/sh

KEY="$1"
INPUT="$2"

killactive()
{
	WIN=$(xprop -root _NET_ACTIVE_WINDOW | awk '{ print $5 }')
	PID=$(xprop -id "$WIN" | grep '_NET_WM_PID' | awk '{ print $3 }')
	kill "$PID"
}

getevts()
{
	while :; do
		xinput test $INPUT
		sleep 1
	done
}

getevts \
	| grep --line-buffered -i "key press *$KEY" \
	| while read -r line; do killactive; done
